language: rust

before_install:
  - sudo apt-get -y install libasound2-dev libudev-dev pkg-config

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
