[package]
name = "rust-8"
version = "0.1.0"
authors = ["Thomas Sullivan <thomas.l.sullivan@vumc.org>"]
edition = "2018"

[[bin]]
name = "r8"
path = "src/main.rs"

[lib]
name = "lib"
path = "src/lib.rs"

[dependencies]
rand = "0.7.0"
sdl2 = "0.34"
